### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/md.obsidian.Obsidian#207]
### Additional feature, program, sandbox permission, etc

Flathub allows changelogs for each new release - can these be automated?

**Comment by joshua-stone** [comment]
This is a feature that I've wanted for a long time, however there isn't currently a reliable way to automate changelog generation because upstream Obsidian doesn't appear to provide changelog information in a way that can be trivially automated. Ideally Obsidian should provide a [`NEWS`](https://github.com/ximion/appstream/blob/main/NEWS) file which can be converted into a metainfo file:

```
$ appstreamcli news-to-metainfo NEWS md.obsidian.Obsidian.metainfo.xml
```

Alternatively, upstream should start maintaining their own [metainfo/appdata](https://github.com/flathub/md.obsidian.Obsidian/blob/master/md.obsidian.Obsidian.appdata.xml) file which contains complete changelog information. It's ultimately their responsibility to provide this data to minimize the burden. [Please file a bug with them.](https://forum.obsidian.md/c/feature-requests/8)
