### ISSUE TITLE
Keep version history

### ISSUE THREAD

**Issue by mamoit** [flathub/md.obsidian.Obsidian#7]
Is there any reason for not keeping a version history?
https://github.com/flathub/md.obsidian.Obsidian/blob/ab304eee8bdd13c940627d084a4b4478b80f5ca5/md.obsidian.Obsidian.appdata.xml#L23

You can check out how other packages do, for eg Riot:
https://github.com/flathub/im.riot.Riot/blob/4cf3b8265c94cb7c02e3e48a2b0e0f52ad3e7583/im.riot.Riot.appdata.xml#L26-L101

**Comment by joshua-stone** [comment]
An unattended job is regularly run to fetch the latest release, and keeping a full version history wasn't a priority when it was written. XML parsing is (admittedly) a bit more complicated than JSON and YAML, so I put quickly together something that merely updates the version in place instead of appending versions:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/update-sources.py#L20

I'd be more than happy to accept patches that can improve the script to retain a full version history. :smile:

**Comment by mamoit** [comment]
There you go :smile:

**Comment by joshua-stone** [comment]
Closing this issue as there hasn't been any activity for some time.
