### ISSUE TITLE
Drag and drop of tabs does not work in Wayland

### ISSUE THREAD

**Issue by smidm** [flathub/md.obsidian.Obsidian#81]
Tabs can't be dropped when running on Wayland. The AppImage version doesn't have the issue. See Obsidian forum for discussion: https://forum.obsidian.md/t/cannot-move-rearrange-panes-when-running-under-wayland/42377/11

**Comment by joshua-stone** [comment]
@smidm A change has been made to fix native titlebars on Wayland:

https://github.com/flathub/md.obsidian.Obsidian/pull/89

Can you see if that addressess the issue?

**Comment by joshua-stone** [comment]
Marking as closed due to lack of activity. Drag-and-drop should work when setting native titlebars too.

**Comment by RenWal** [comment]
This is still an issue in version 1.2.7 shipped via Flatpak (Ubuntu 22.04, Gnome, Wayland, Intel graphics).

Passing `OBSIDIAN_USE_WAYLAND=0` (causing xwayland to be used) is a workaround.

#89 does not fix the issue.

**Comment by joshua-stone** [comment]
@RenWal This is an [upstream issue that impacts all builds](https://forum.obsidian.md/t/cannot-move-rearrange-panes-when-running-under-wayland/42377), which is why Wayland support is still experimental and [`OBSIDIAN_USE_WAYLAND=0`](https://github.com/flathub/md.obsidian.Obsidian/blob/e6f8639803f2258dde76409326d824f5d1bd125d/md.obsidian.Obsidian.yml#L31) is the default setting.
