### ISSUE TITLE
Update flatpak notification is actually a downgrade?

### ISSUE THREAD

**Issue by MavropaliasG** [flathub/md.obsidian.Obsidian#9]
Hi I got an update notification in Manjaro Linux for a new version of Obsidian, and while I have 0.11.9, it prompts me to 'update' to 0.11.5?

![image](https://user-images.githubusercontent.com/13523909/112718667-7b4fe300-8f2f-11eb-8db6-e7cc5468e9d9.png)

**Comment by lishid** [comment]
The version on flathub is the installer version - which comes with the Electron engine + possibly an older version of the Obsidian. The engine then updates the internal app without having to re-download Electron.

You're likely using an older version of the installer (pre 0.11.5) which has automatically updated to 0.11.9. flatpak is telling you to upgrade the engine to 0.11.5 since that's the latest on flathub.

You can check your engine (installer) version in Settings > About.

**Comment by MavropaliasG** [comment]
Perhaps, or maybe 93a6374bdfad84066ee1a5d9c1b5d72188a10fcf fixed it (it's showin the correct version now)

![image](https://user-images.githubusercontent.com/13523909/112751443-ace4af00-9000-11eb-9a7b-5290883d062d.png)
